on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: "https://hooks.slack.com/services/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"
        SLACK_COLOR: "danger"
        SLACK_MESSAGE: "<!channel>\nEnv: STG\nMsg: apkのアップロードに失敗しました:cry:"
