
name: Product
on:
  push:
    tags:
      - /v*
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Version
        id: get_version
        run: echo "number-part=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      - name: Display
        run: echo ${{ steps.get_version.outputs.number-part }}
      - name: Dispaly git count
        run: 
          git rev-list @ --count   
#one step
#two step
